### ISSUE TITLE
SyntaxError: unexpected token

### ISSUE THREAD

**Issue by gbishop** [nightwolfz/mobx-starter#1]
Newb here looking for starters and I ran into a problem. I cloned, then `npm install`, then `npm run dev` as suggested and I get:

```
mobx-starter (master)$ npm run dev

> mobx-starter@0.1.0 dev /home/gb/tmp/mobx-starter
> cross-env NODE_ENV=development node ./index.js

/home/gb/tmp/mobx-starter/src/server/routes/account.js:145
        const { session } = req;
              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/home/gb/tmp/mobx-starter/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/gb/tmp/mobx-starter/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gb/tmp/mobx-starter/src/server/index.js:133:17)
    at Module._compile (module.js:410:26)
    at loader (/home/gb/tmp/mobx-starter/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/gb/tmp/mobx-starter/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gb/tmp/mobx-starter/index.js:12:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! mobx-starter@0.1.0 dev: `cross-env NODE_ENV=development node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mobx-starter@0.1.0 dev script 'cross-env NODE_ENV=development node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mobx-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mobx-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mobx-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gb/tmp/mobx-starter/npm-debug.log
```

**Comment by nightwolfz** [comment]
You must be running node 6 or higher for that syntax (destructuring) to work properly.

Otherwise, you can always add a few more babel plugins to make everything work on node v4.

Open your `.babelrc` file and change it to

```
{
  "plugins": [
    "add-module-exports",
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-es2015-modules-commonjs",
    "transform-es2015-arrow-functions",
    "transform-es2015-block-scoping",
    "transform-es2015-block-scoped-functions",
    "transform-es2015-classes",
    "transform-es2015-computed-properties",
    "transform-es2015-destructuring",
    "transform-es2015-literals",
    "transform-es2015-template-literals",
    "transform-es2015-parameters",
    "transform-es2015-shorthand-properties",
    "transform-es2015-spread",
    "transform-react-jsx",
    "syntax-async-functions",
    "fast-async"
  ]
}
```

Hopefully that does the trick!

**Comment by gbishop** [comment]
Thanks for the response. 

After adding that change I get this:

```
npm run dev

> mobx-starter@0.1.0 dev /home/gb/tmp/mobx-starter
> cross-env NODE_ENV=development node ./index.js

[Static] /build - /home/gb/tmp/mobx-starter/build
/home/gb/tmp/mobx-starter/index.js:28
if (process.argv.slice(2).includes('-m')) {
                          ^

TypeError: process.argv.slice(...).includes is not a function
    at Object.<anonymous> (/home/gb/tmp/mobx-starter/index.js:28:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by gbishop** [comment]
I installed nvm which allows me to switch to node 6 and these issues go away.
