### ISSUE TITLE
Error: webpack.base.js: The resolved config file doesn't contain a resolve configuration

### ISSUE THREAD

**Issue by equicolor** [nightwolfz/mobx-starter#13]
I can't start mobx-starter application on Windows 7. This is output of `npm run dev` command on clean mobx-starter installation:
```
> npm run dev

> mobx-starter@1.0.0 dev c:\OpenServer\domains\ads\mobx-starter
> cross-env NODE_ENV=development nodemon ./index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: c:\OpenServer\domains\ads\mobx-starter\src\server/**/* src/shared
[nodemon] starting `node ./index.js`
C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-core\lib\transformation\file\index.js:578
        throw err;
        ^

Error: c:/OpenServer/domains/ads/mobx-starter/core/webpack/webpack.base.js: The resolved config file doesn't contain a resolve configuration
    at PluginPass.CallExpression (c:\OpenServer\domains\ads\mobx-starter\node_modules\babel-plugin-webpack-alias\build\index.js:48:27)
    at newFn (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\OpenServer\domains\ads\mobx-starter\node_modules\babel-traverse\lib\path\context.js:115:19)
 [nodemon] app crashed - waiting for file changes before starting...

```
> npm -v
3.8.6
> node -v
v6.1.0
> os
Windows 7 64bit
```

**Comment by nightwolfz** [comment]
@equicolor 

It seems to be a bug in the "babel-plugin-webpack-alias" plugin. I can't reproduce it on Windows 10 though (same node version).

Can you try using version 2.1.0 and if it doesn't work, version 1.8.2 of that plugin ?
