### ISSUE TITLE
branch next won't run

### ISSUE THREAD

**Issue by zorganovic** [nightwolfz/mobx-starter#30]
Hi

After pulling next, npm install and npm run dev I got this error
vagrant@dev-ts:~/projects/mobx-starter$ npm run dev
mobx-starter@2.0.0 dev /home/vagrant/projects/mobx-starter
cross-env NODE_ENV=development nodemon ./index.js
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/vagrant/projects/mobx-starter/core/**/* src/client/stores.js src/client/preload.js /home/vagrant/projects/mobx-starter/server/**/*
[nodemon] starting `node ./index.js`
/home/vagrant/projects/mobx-starter/node_modules/koa-mount/index.js:48
  return async function (ctx, upstream){
               ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/projects/mobx-starter/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/projects/mobx-starter/server/server.js:5:1)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by zorganovic** [comment]
Using node 8 solved the problem :+1:
